language: none
mono: none
sudo: required
dist: xenial
install:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2
script:
  - dotnet build
  - dotnet pack
  - cd pdbs;bash ./download.sh;cd ../
  - dotnet test
