language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 2.2
script:
  - dotnet build
  - dotnet pack
  - cd pdbs;bash ./download.sh;cd ../
  - dotnet test Tests/SharpPdb.Windows.Tests/SharpPdb.Windows.Tests.csproj
  - dotnet test Tests/SharpPdb.Tests/SharpPdb.Tests.csproj
